# Generated by Django 4.1.7 on 2023-08-13 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_notifications_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memories',
            old_name='video',
            new_name='image',
        ),
    ]
